### ISSUE TITLE
rename GenesisProtocolExecuteInterface and GenesisProtocolCallbacksInterface

### ISSUE THREAD

**Issue by dkent600** [daostack/infra#10]
All of voting machines assume that the contract using them is implementing `GenesisProtocolExecuteInterface` and `GenesisProtocolCallbacksInterface`.

Do the names of these interfaces really imply anything about GenesisProtocol or voting machines/schemes in general?

Would it make more sense to be named something more generic like `ProposalExecuteInterface` and `ContractCallbacksInterface`?

Otherwise it is confusing to those reading the code, and we could do well to document the reasons behind the naming.

**Comment by orenyodfat** [comment]
ProposalExecuteInterface
VotingCallbacksInterface
