### ISSUE TITLE
GenesisProtocol overrides staking token in constructor

### ISSUE THREAD

**Issue by dkent600** [daostack/infra#13]
On this line: 

https://github.com/daostack/infra/blob/732af4df82471288e0168ad74d7520da81bf1072/contracts/VotingMachines/GenesisProtocol.sol#L122

The GenesisProtocol overrides any staking token given in its constructor.  Why is this?  Can this be either fixed or documented in the code?

**Comment by orenyodfat** [comment]
The GEN token (staking token) address is hard coded in the contract by GEN_TOKEN_ADDRESS .
This will work for a network which already hosted the GEN token on this address (mainnet , kovan...).
If such contract does not exist in the network (e.g ganache)  this ` if (isContract(address(GEN_TOKEN_ADDRESS)))`  will turn to false and will use the token address passed by the constructor. 
Yea, might worth to add a small comment in the code.

**Comment by dkent600** [comment]
What if someone doesn't want to use GEN even though it exists on the network?

**Comment by orenyodfat** [comment]
It cannot use daostack gp contract

**Comment by orenyodfat** [comment]
The Staking token is gen

**Comment by orenyodfat** [comment]
We will
