### ISSUE TITLE
GenesisProtocol.getBoostedProposalsCount and GenesisProtocol.threshold no longer work for an entire avatar

### ISSUE THREAD

**Issue by dkent600** [daostack/infra#21]
With `GenesisProtocol.getBoostedProposalsCount` and `GenesisProtocol.threshold` we used to be able to pass an avatar address and obtain results scoped to the entire given avatar.  But that no longer works.  These two functions now take an `organizationId` that is scoped to the set of proposals created by whatever is implied by the `organizationId`, for example, `ContributionReward` plus the avatar.

This is a significant change in behavior and I wonder if it is intended.

`ContributionReward` (for example) may not be the only contract registered with an avatar that is using a given GenesisProtocol.  Yet `threshold`, for example, it seems to me should be scoped to the entire avatar.  So should the number of boosted proposals.

**Comment by orenyodfat** [comment]
Yes. it is intended. 
Each "proposal creator" (in ARC it is called scheme) has its own queue of proposals.

**Comment by dkent600** [comment]
@orenyodfat 

This will be some additional work then to reproduce the prior functionality in Arc.js for `GenesisProtocol.getBoostedProposalsCount`.  However the prior behavior of `GenesisProtocol.threshold` will no longer be possible to reproduce.  How to combine thresholds across multiple ogranizationIds?

I'm concerned about `GenesisProtocol.threshold`.  Isn't the threshold supposed to funnel attention of the entire DAO?  As currently implemented, DAOs that have multiple proposal-generating schemes will have different thresholds for each scheme rather than one threshold for the whole DAO.  Is this really the intent?

**Comment by orenyodfat** [comment]
Yes. this is the intent
