### ISSUE TITLE
Gen staked for boosted proposal which was then voted against is left in the genesis protocol contract.

### ISSUE THREAD

**Issue by A-Zak** [daostack/infra#59]
When a proposal is created, the dao is staking against it.
If then it is staked for and it is boosted, but eventually voted against - some of the gen is going to the other people that voted against, but the DAOs relative part stays in the genesis contract.

<img width="1297" alt="Screenshot 2019-04-18 at 1 39 12" src="https://user-images.githubusercontent.com/302774/56325671-bf4ee080-617b-11e9-927d-9860e8b529dd.png">
https://rinkeby.etherscan.io/address/0x817a0600e9dc9dbaae12e13c5c0111398240e273#tokentxns

**Comment by orenyodfat** [comment]
please send the tx which try to redeem the Dao  winning.

**Comment by A-Zak** [comment]
@orenyodfat how can I redeem the DAO winning? who is allowed to do it?

**Comment by orenyodfat** [comment]
Same as you redeem for anyone else .
Set the beneficiary as the avatar.

**Comment by A-Zak** [comment]
Ok I have managed to get the money out for the dao.
The only question left is who will pay for the gas for these transactions........
