### ISSUE TITLE
What happens with stakes for / against proposals that have expiredInQueue?

### ISSUE THREAD

**Issue by A-Zak** [daostack/infra#60]
If a proposal expiresInQueue, what happens to the gens that were staked for / against this proposal? 

• using the redemptions mechanism? 
• by calling the execute method?
• Is there an external motivation mechanism there (like the executeBoosted)?

**Comment by orenyodfat** [comment]
in that case there is no decision . each staker can gets back its own stakes.
using the redeem function.
yes, first , someone need to call the redeem function.
- there is no explicit incentive for that as there is no need for  : the incentive is build in as you would like to get your stakes back. and also there is no meaning for the timing of the execute (not like with the boosted case).
