### ISSUE TITLE
GP doesn't fire StateChange event when proposal moves to QuietEndingPeriod

### ISSUE THREAD

**Issue by ben-kaufman** [daostack/infra#61]
When changing the state of a proposal to QuietEndingPeriod Genesis protocol currently doesn't emit a `StateChange` event as it would be expected to do and currently does for all other state changes.

Genesis protocol should emit a `StateChange` event here:
https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L706

**Comment by orenyodfat** [comment]
This is nice to have though it is not a must .

Subgraph already read the proposal upon voting event and should also update
its state
