### ISSUE TITLE
AbsoluteVote doesnt work when total reputation<100

### ISSUE THREAD

**Issue by sirpy** [daostack/infra#89]
in the method _execute you do DIV before MUL
if(votes > totalReputation/100*precReq)
this of course becomes 0 when totalReputation<100
always mul before div

**Comment by orenyodfat** [comment]
this done in purpose to prevent overflow https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L511 .
yes, if total rep < 100 it will not work , though normally, and in the very most of the cases, total rep will be higher than 100.
reputation is in wei units.

**Comment by sirpy** [comment]
i would say that the overflow multiplying by 0-100 is the extreme case. but ok.
in any case  dont you think a require is needed in order to check for overflow/underflow? like using SafeMath?
or force DAO to have at least 100 rep?

**Comment by orenyodfat** [comment]
overflow multiple total reputation in wei uints 1 rep = 10^18 is not so extreme case.
adding a require for the very edge case of total rep<100 is redundant and not worth the addition gas for the check on each call.
divided by 100 and then multiple by a value which is capped by 100 (params.queuedVoteRequiredPercentage) will do the work.
